### ISSUE TITLE
SameFileError 异常

### ISSUE THREAD

**Issue by danerlt** [iWoz/file_sync#3]
Hi，iWoz,我在使用`python file_sync`的时候发现把config目录下的file_list.txt和README.md文件都加入到file_list.txt里面，在执行代码里面的copy方法复制的时候会抛出`SameFileError`,这种情况怎么解决呀?
```
H:\config\file_sync>python file_sync.py
Traceback (most recent call last):
  File "file_sync.py", line 54, in <module>
    copy(file_path, DIR_FOR_GIT)
  File "C:\Program Files\Anaconda3\lib\shutil.py", line 241, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Program Files\Anaconda3\lib\shutil.py", line 104, in copyfile
    raise SameFileError("{!r} and {!r} are the same file".format(src, dst))
shutil.SameFileError: 'H:/config/README.md' and 'H:\\config\\README.md' are the same file

H:\config\file_sync>python file_sync.py
Traceback (most recent call last):
  File "file_sync.py", line 54, in <module>
    copy(file_path, DIR_FOR_GIT)
  File "C:\Program Files\Anaconda3\lib\shutil.py", line 241, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Program Files\Anaconda3\lib\shutil.py", line 104, in copyfile
    raise SameFileError("{!r} and {!r} are the same file".format(src, dst))
shutil.SameFileError: 'H:/config/README.md' and
```

**Comment by iWoz** [comment]
抱歉，现在才回。
将两个文件的路径移出file_list.txt，file_list.txt只用来同步需要同步的文件，而file_list.txt本身则不需要被同步，具体用法请参考readme和https://github.com/iWoz/configs
